package com.componentes;

/*
 * API Consulta de Saldo de Factura
 * API para Consulta de Saldo de Factura
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import java.util.Objects;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * FacturaInterna
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-10T01:24:44.057Z")
@XmlRootElement
public class FacturaInterna {
	private Integer idFactura = null;

	private String descripcion = null;

	private BigDecimal saldoAPagar = null;

	public FacturaInterna idFactura(Integer idFactura) {
		this.idFactura = idFactura;
		return this;
	}
	
	public FacturaInterna idFactura(Integer idFactura, BigDecimal saldoAPagar) {
		this.idFactura = idFactura;
		this.saldoAPagar = saldoAPagar;
		return this;
	}

	/**
	 * Get id
	 * 
	 * @return id
	 **/
	public Integer getIdFactura() {
		return idFactura;
	}

	public void setIdFactura(Integer idFactura) {
		this.idFactura = idFactura;
	}

	public FacturaInterna descripcion(String descripcion) {
		this.descripcion = descripcion;
		return this;
	}

	/**
	 * Get descripcion
	 * 
	 * @return descripcion
	 **/
	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public FacturaInterna saldoAPagar(BigDecimal saldoAPagar) {
		this.saldoAPagar = saldoAPagar;
		return this;
	}

	/**
	 * Get saldoAPagar
	 * 
	 * @return saldoAPagar
	 **/
	public BigDecimal getSaldoAPagar() {
		return saldoAPagar;
	}

	public void setSaldoAPagar(BigDecimal saldoAPagar) {
		this.saldoAPagar = saldoAPagar;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		FacturaInterna facturaInterna = (FacturaInterna) o;
		return Objects.equals(this.idFactura, facturaInterna.idFactura)
				&& Objects.equals(this.descripcion, facturaInterna.descripcion)
				&& Objects.equals(this.saldoAPagar, facturaInterna.saldoAPagar);
	}

	@Override
	public int hashCode() {
		return Objects.hash(idFactura, descripcion, saldoAPagar);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class FacturaInterna {\n");

		sb.append("    id: ").append(toIndentedString(idFactura)).append("\n");
		sb.append("    descripcion: ").append(toIndentedString(descripcion)).append("\n");
		sb.append("    saldoAPagar: ").append(toIndentedString(saldoAPagar)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}
}