/*
 * API de compensación de Factura
 * API para Compensación de Factura
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.componentes;

import java.util.Objects;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Resultado
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-10T20:55:28.067Z")
@XmlRootElement
public class ResultadoInterno {
  private Integer idFactura = null;

  private String descripcion = null;

  public ResultadoInterno idFactura(Integer idFactura) {
    this.idFactura = idFactura;
    return this;
  }

   /**
   * Get idFactura
   * @return idFactura
  **/
  public Integer getIdFactura() {
    return idFactura;
  }

  public void setIdFactura(Integer idFactura) {
    this.idFactura = idFactura;
  }

  public ResultadoInterno descripcion(String descripcion) {
    this.descripcion = descripcion;
    return this;
  }

   /**
   * Get descripcion
   * @return descripcion
  **/
  public String getDescripcion() {
    return descripcion;
  }

  public void setDescripcion(String descripcion) {
    this.descripcion = descripcion;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResultadoInterno resultado = (ResultadoInterno) o;
    return Objects.equals(this.idFactura, resultado.idFactura) &&
        Objects.equals(this.descripcion, resultado.descripcion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idFactura, descripcion);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Resultado {\n");
    
    sb.append("    idFactura: ").append(toIndentedString(idFactura)).append("\n");
    sb.append("    descripcion: ").append(toIndentedString(descripcion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

